### ISSUE TITLE
Doesn't support ActiveRecord 5.0

### ISSUE THREAD

**Issue by jaimerodas** [joker1007/activemodel-associations#12]
Even though the README states that this gem supports AR 5, the [gemspec](/joker1007/activemodel-associations/blob/master/activemodel-associations.gemspec#L21) specifically requires versions below it. Am I doing something wrong?

**Comment by joker1007** [comment]
I had ready to support AR-5.0, but I forgot to release 😓 
Today, I got the time to release new version which supports AR-5.0.
Thanks for your report !!

**Comment by jaimerodas** [comment]
Thanks!
