### ISSUE TITLE
Compatibility issue with ActiveRecord 4.2

### ISSUE THREAD

**Issue by paulleader** [joker1007/activemodel-associations#2]
ActiveModel::Associations seems to be incompatible with Rails 4.2 at the moment.

Any attempt to access a has_many relationship throws the exception `undefined method new_record?' for #<MyClass:[object_id]>`

It looks like ActiveRecord 4.2 is calling new_record? on 'owner' (i.e. my object) at line 36 of `lib/active_record/associations/collection_association.rb`.

Looking at the surrounding code I think this is to do with caching, although I've not had time to dig much.

Adding this to the classes that include ActiveRecord::Associations seems to solve the immediate problem, however I don't know what the knockon effects might be yet.

```ruby
def new_record?
  true
end
```

**Comment by joker1007** [comment]
Thank you for your report!! :smile: 
I have already fixed it.
But I find other probrem on polymorphic association, I don't release next version yet.
I will fix and release soon. please wait.

**Comment by joker1007** [comment]
I have released. :rocket:

**Comment by paulleader** [comment]
:+1: 

Thankyou :smile:
