### ISSUE TITLE
 undefined method `prepend' for ActiveRecord::Associations::AssociationScope:Class

### ISSUE THREAD

**Issue by jbmyid** [joker1007/activemodel-associations#6]
I am using Rails 4.1.0 and jruby 1.7.13
not able to start server.

NoMethodError: undefined method `prepend' for ActiveRecord::Associations::AssociationScope:Class
                                    init at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/activemodel-associations-0.1.1/lib/active_model/associations/hooks.rb:6
                           instance_eval at org/jruby/RubyBasicObject.java:1533
                            execute_hook at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/activesupport-4.1.0/lib/active_support/lazy_load_hooks.rb:38
                                 on_load at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/activesupport-4.1.0/lib/active_support/lazy_load_hooks.rb:28
                                    each at org/jruby/RubyArray.java:1613
                                 on_load at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/activesupport-4.1.0/lib/active_support/lazy_load_hooks.rb:27
                                    init at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/activemodel-associations-0.1.1/lib/active_model/associations/hooks.rb:4
                                 Railtie at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/activemodel-associations-0.1.1/lib/active_model/associations/railtie.rb:4
                           instance_exec at org/jruby/RubyBasicObject.java:1562
                                     run at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/railties-4.1.0/lib/rails/initializable.rb:30
                        run_initializers at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/railties-4.1.0/lib/rails/initializable.rb:55
                              tsort_each at /home/jalendra/.rvm/rubies/jruby-1.7.13/lib/ruby/1.9/tsort.rb:150
       each_strongly_connected_component at /home/jalendra/.rvm/rubies/jruby-1.7.13/lib/ruby/1.9/tsort.rb:183
  each_strongly_connected_component_from at /home/jalendra/.rvm/rubies/jruby-1.7.13/lib/ruby/1.9/tsort.rb:219
       each_strongly_connected_component at /home/jalendra/.rvm/rubies/jruby-1.7.13/lib/ruby/1.9/tsort.rb:182
                                    each at org/jruby/RubyArray.java:1613
       each_strongly_connected_component at /home/jalendra/.rvm/rubies/jruby-1.7.13/lib/ruby/1.9/tsort.rb:180
                              tsort_each at /home/jalendra/.rvm/rubies/jruby-1.7.13/lib/ruby/1.9/tsort.rb:148
                        run_initializers at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/railties-4.1.0/lib/rails/initializable.rb:54
                             initialize! at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/railties-4.1.0/lib/rails/application.rb:288
                                  (root) at /home/jalendra/Documents/Projects/avaamo-server/server/config/environment.rb:5
                                 require at org/jruby/RubyKernel.java:1065
                                 require at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247
                         load_dependency at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232
                                 require at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247
                                  (root) at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/railties-4.1.0/lib/rails/application.rb:1
                    require_environment! at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/railties-4.1.0/lib/rails/application.rb:264
    require_application_and_environment! at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:147
                                 console at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:68
                            run_command! at /home/jalendra/.rvm/gems/jruby-1.7.13/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:40
                                 require at org/jruby/RubyKernel.java:1065
                                  (root) at bin/rails:4

**Comment by joker1007** [comment]
Sorry, this gem requires ruby-2.0.0 feature. (Module#prepend)
Please upgrade jruby version to jruby-9000 or later.

I will add description of ruby platform requirement to README.
