### ISSUE TITLE
Use for nested attributes?

### ISSUE THREAD

**Issue by jessieay** [joker1007/activemodel-associations#8]
Hello! I am looking for a way to use `accepts_nested_attributes` on an ActiveRecord class where the nested object is not an ActiveRecord class. 

The parent class (backed by ActiveRecord) is called `Manifest`. I have another class, where I am including `ActiveModel::Associations` called `Transporter`.

I would like `Manifest` to `have_many: :transporters` and also accept nested attributes so I can include them on the same form in a Railsy way.

I just tried this and am getting this error when I try to load my form:

> undefined method `relation_delegate_class' for Transporter:Class

Before I go further in debugging this, I am wondering if having nested attributes for an active model model is a desired use case for this library, or if I should look elsewhere. Part of me is thinking that I should just make `Transporter` into an ActiveRecord class, but hoping I won't have to.

Thank you!

Jessie

**Comment by joker1007** [comment]
Sorry, I did not consider the use case.
main purpose of this gem is to access `ActiveRecord` based class from `ActiveModel` class easily.
It is difficult to add `accepts_nested_attributes` feature to this gem. 

I think that it is better to implement setter method for nested_attributes by yourself.

**Comment by jessieay** [comment]
@joker1007 thank you for the reply! Based on this information, I think I am going to go down a different path for this feature.

Thanks again,

Jessie
